FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ENV NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_BUSINESS_NAME
ARG NEXT_PUBLIC_BUSINESS_REGISTRATION_NUMBER
ARG NEXT_PUBLIC_BUSINESS_REPRESENTATIVE
ARG NEXT_PUBLIC_BUSINESS_ADDRESS
ARG NEXT_PUBLIC_BUSINESS_PHONE
ARG NEXT_PUBLIC_BUSINESS_EMAIL
ENV NEXT_PUBLIC_BUSINESS_NAME=$NEXT_PUBLIC_BUSINESS_NAME
ENV NEXT_PUBLIC_BUSINESS_REGISTRATION_NUMBER=$NEXT_PUBLIC_BUSINESS_REGISTRATION_NUMBER
ENV NEXT_PUBLIC_BUSINESS_REPRESENTATIVE=$NEXT_PUBLIC_BUSINESS_REPRESENTATIVE
ENV NEXT_PUBLIC_BUSINESS_ADDRESS=$NEXT_PUBLIC_BUSINESS_ADDRESS
ENV NEXT_PUBLIC_BUSINESS_PHONE=$NEXT_PUBLIC_BUSINESS_PHONE
ENV NEXT_PUBLIC_BUSINESS_EMAIL=$NEXT_PUBLIC_BUSINESS_EMAIL
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
